
environment:
  matrix:
    - nodejs_version: "6"

cache:
  - node_modules -> package.json

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node $env:nodejs_version
  - git reset --hard HEAD
  - npm install -g npm@latest
  - yarn add electron-builder@next
  - yarn

test_script:
  - yarn versions
  - yarn test

build_script:
  - yarn dist
