version: 0.1.{build}
skip_tags: true

platform:
  - x64

cache:
- node_modules

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - git reset --hard HEAD
  - npm install npm -g
  - yarn

test_script:
  - yarn test

build_script:
  - node --version
  - npm --version
  - yarn release
