build: off

os: unstable

skip_tags: true

environment:
  matrix:
    - nodejs_version: "6"

cache:
  - node_modules -> package.json

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm@latest
  - yarn add electron-builder@next
  - yarn

test_script:
  - yarn versions
  - yarn test

build_script:
  - yarn release
