function initApartment() {

  var office = new THREE.Group()
  var officeShadows = new THREE.Geometry()

  // Foundation
  var found = new THREE.BoxGeometry(8, .5, 8)
  var step = new THREE.BoxGeometry(8.25, .25, 8.25)
  step.translate(0, -.125, 0)
  found.merge(step)
  var foundShadow = found.clone(true)
  officeShadows.merge(found)
  var buildingFound = new THREE.Mesh(found, foundation)
  buildingFound.castShadow = true
  office.add(buildingFound)

  // Outside Walls
  var base = new THREE.Geometry()
  var left = new THREE.BoxGeometry(.5, 10, 1)
  left.translate(-3.5, 5.25, 3.25)
	base.merge(left)
  left.translate(0, 0, -2.125)
	base.merge(left)
  left.translate(0, 0, -2.125)
	base.merge(left)
  left.translate(0, 0, -2.125)
	base.merge(left)
  left.translate(7, 0, 0)
	base.merge(left)
  left.translate(0, 0, 2.125)
	base.merge(left)
  left.translate(0, 0, 2.125)
	base.merge(left)
  left.translate(0, 0, 2.125)
	base.merge(left)
  var back = new THREE.BoxGeometry(1, 10, .5)
  back.translate(-1.5, 5.25, -3.375)
	base.merge(back)
  back.translate(3, 0, 0)
	base.merge(back)
  back.translate(0, 0, 6.875)
	base.merge(back)
  back.translate(-3, 0, 0)
	base.merge(back)
  var backSide = new THREE.BoxGeometry(1.25, 3.5, .5)
  backSide.translate(-2.625, 2, 3.5)
	base.merge(backSide)
  backSide.translate(5.25, 0, 0)
	base.merge(backSide)
  backSide.translate(0, 0, -6.875)
	base.merge(backSide)
  backSide.translate(-5.25, 0, 0)
	base.merge(backSide)
  var front = new THREE.BoxGeometry(1.25, 1.75, .5)
  front.translate(-2.625, 6.25, 3.5)
	base.merge(front)
  front.translate(0, 3.125, 0)
	base.merge(front)
  front.translate(5.25, 0, 0)
	base.merge(front)
  front.translate(0, -3.125, 0)
	base.merge(front)
  front.translate(0, 0, -6.875)
	base.merge(front)
  front.translate(0, 3.125, 0)
	base.merge(front)
  front.translate(-5.25, 0, 0)
	base.merge(front)
  front.translate(0, -3.125, 0)
	base.merge(front)
  var front = new THREE.BoxGeometry(2, 7.5, .5)
  front.translate(0, 6.5, 3.5)
	base.merge(front)
  var front = new THREE.BoxGeometry(2, 10, .5)
  front.translate(0, 5.25, -3.375)
	base.merge(front)
  var side = new THREE.BoxGeometry(.5, 3.5, 1.15)
  side.translate(-3.5, 2, 2.19)
	base.merge(side)
  side.translate(0, 0, -2.125)
	base.merge(side)
  side.translate(0, 0, -2.125)
	base.merge(side)
  side.translate(7, 0, 0)
	base.merge(side)
  side.translate(0, 0, 2.125)
	base.merge(side)
  side.translate(0, 0, 2.125)
	base.merge(side)
  var side = new THREE.BoxGeometry(.5, 1.75, 1.15)
  side.translate(-3.5, 6.25, 2.19)
	base.merge(side)
  side.translate(0, 0, -2.125)
	base.merge(side)
  side.translate(0, 0, -2.125)
	base.merge(side)
  side.translate(7, 0, 0)
	base.merge(side)
  side.translate(0, 0, 2.125)
	base.merge(side)
  side.translate(0, 0, 2.125)
	base.merge(side)
  side.translate(0, 3.125, 0)
	base.merge(side)
  side.translate(0, 0, -2.125)
	base.merge(side)
  side.translate(0, 0, -2.125)
	base.merge(side)
  side.translate(-7, 0, 0)
	base.merge(side)
  side.translate(0, 0, 2.125)
	base.merge(side)
  side.translate(0, 0, 2.125)
	base.merge(side)
  var floor = new THREE.BoxGeometry(6.5, .25, 6.5)
  floor.translate(0, 3, 0)
	base.merge(floor)
  floor.translate(0, 3.5, 0)
	base.merge(floor)
  floor.translate(0, 3.63, 0)
	base.merge(floor)
  var innerWall = new THREE.BoxGeometry(.25, 7.25, 6.5)
  innerWall.translate(0, 6.67, 0)
	base.merge(innerWall)

  // Windows
  var windows = new THREE.Geometry()
  var windowSide = new THREE.BoxGeometry(7, 9.5, .1)
  windowSide.translate(0, 5, 3.5)
	windows.merge(windowSide)
  windowSide.translate(0, 0, -7)
	windows.merge(windowSide)
  var windowSide = new THREE.BoxGeometry(.1, 9.5, 7)
  windowSide.translate(3.5, 5, 0)
	windows.merge(windowSide)
  windowSide.translate(-7, 0, 0)
	windows.merge(windowSide)
  var windowMesh = new THREE.Mesh(windows, windowColor)
  office.add(windowMesh)



  // roof
	var cap = new THREE.Geometry()
  var capLeft = new THREE.BoxGeometry(.25, .5, 7.375)
	capLeft.translate(-3.88, 10.5, .05)
	cap.merge(capLeft)
	capLeft.translate(7.76, 0, 0)
	cap.merge(capLeft)
  var capFront = new THREE.BoxGeometry(8.01, .5, .25)
	capFront.translate(0, 10.5, 3.86)
	cap.merge(capFront)
	capFront.translate(0, 0, -7.6)
	cap.merge(capFront)
  // sill
  // fronts - bottom
  var sillBottom = new THREE.Geometry()
  var sill1 = new THREE.BoxGeometry(1.5, .1, .1)
	sill1.translate(-2.6, 7.125, 3.8)
	sillBottom.merge(sill1)
	sill1.translate(0, 0, -7.475)
	sillBottom.merge(sill1)
  var sill2 = new THREE.BoxGeometry(1.22, .1, .5)
	sill2.translate(-2.62, 7.125, 3.5)
	sillBottom.merge(sill2)
	sill2.translate(0, 0, -6.875)
	sillBottom.merge(sill2)
	cap.merge(sillBottom)
	sillBottom.translate(5.25, 0, 0)
	cap.merge(sillBottom)
	sillBottom.translate(0, -3.375, 0)
	cap.merge(sillBottom)
	sillBottom.translate(-5.25, 0, 0)
	cap.merge(sillBottom)
  // fronts - top
  var sillTop = new THREE.Geometry()
  var sill3 = new THREE.BoxGeometry(1.375, .1, .1)
	sill3.translate(-2.6, 8.5, 3.8)
	sillTop.merge(sill3)
	sill3.translate(0, 0, -7.475)
	sillTop.merge(sill3)
  var sill4 = new THREE.BoxGeometry(1.25, .1, .1)
	sill4.translate(-2.625, 7.75, 3.55)
	sillTop.merge(sill4)
	sill4.translate(0, 0, -7.1)
	sillTop.merge(sill4)
	cap.merge(sillTop)
	sillTop.translate(5.25, 0, 0)
	cap.merge(sillTop)
	sillTop.translate(0, -3.12, 0)
	cap.merge(sillTop)
	sillTop.translate(-5.25, 0, 0)
	cap.merge(sillTop)
  //sides-Top
  var sillTopSide = new THREE.Geometry()
  var sill = new THREE.BoxGeometry(.1, .1, 1.375)
	sill.translate(3.8, 8.5, 2.175)
	sillTopSide.merge(sill)
	sill.translate(-7.6, 0, 0)
	sillTopSide.merge(sill)
  var sill2 = new THREE.BoxGeometry(.1, .1, 1.25)
	sill2.translate(3.55, 7.75, 2.175)
	sillTopSide.merge(sill2)
	sill2.translate(-7.1, 0, 0)
	sillTopSide.merge(sill2)
	cap.merge(sillTopSide)
	sillTopSide.translate(0, 0, -2.125)
	cap.merge(sillTopSide)
	sillTopSide.translate(0, 0, -2.125)
	cap.merge(sillTopSide)
	sillTopSide.translate(0, -3.125, 0)
	cap.merge(sillTopSide)
	sillTopSide.translate(0, 0, 2.125)
	cap.merge(sillTopSide)
	sillTopSide.translate(0, 0, 2.125)
	cap.merge(sillTopSide)
  var sillBottomSide = new THREE.Geometry()
  var sill3 = new THREE.BoxGeometry(.1, .1, 1.5)
	sill3.translate(3.8, 7.1, 2.175)
	sillBottomSide.merge(sill3)
	sill3.translate(-7.6, 0, 0)
	sillBottomSide.merge(sill3)
  var sill4 = new THREE.BoxGeometry(.5, .1, 1.22)
	sill4.translate(3.51, 7.1, 2.175)
	sillBottomSide.merge(sill4)
	sill4.translate(-7.02, 0, 0)
	sillBottomSide.merge(sill4)
	cap.merge(sillBottomSide)
	sillBottomSide.translate(0, 0, -2.125)
	cap.merge(sillBottomSide)
	sillBottomSide.translate(0, 0, -2.125)
	cap.merge(sillBottomSide)
	sillBottomSide.translate(0, -3.37, 0)
	cap.merge(sillBottomSide)
	sillBottomSide.translate(0, 0, 2.125)
	cap.merge(sillBottomSide)
	sillBottomSide.translate(0, 0, 2.125)
	cap.merge(sillBottomSide)
  // Door
  var doorSill = new THREE.BoxGeometry(2.5, .25, .2)
	doorSill.translate(0, 2.87, 3.75)
	cap.merge(doorSill)
  var doorSillSide = new THREE.BoxGeometry(.1, 2.5, .1)
	doorSillSide.translate(-1, 1.5, 3.75)
	cap.merge(doorSillSide)
	doorSillSide.translate(1, 0, 0)
	cap.merge(doorSillSide)
	doorSillSide.translate(1, 0, 0)
	cap.merge(doorSillSide)
  // add to building
  var roofShadow = cap.clone(true)
  officeShadows.merge(roofShadow)
  var roof = new THREE.Mesh(cap, foundation)
  roof.castShadow = true
  office.add(roof)

  // Assemble
  var baseShadow = base.clone(true)
  officeShadows.merge(baseShadow)
  var building = new THREE.Mesh(base, brick)
  building.castShadow = true
  office.add(building)
  var buildingShadows = new THREE.Mesh(officeShadows, shadows)
  buildingShadows.receiveShadow = true
  office.add(buildingShadows)

  // Set Decorations
  var decorations = new THREE.Group()
  var decorationShadows = new THREE.Geometry()
  // Couch
  var couchGeometry = new THREE.Geometry()
  var couchSeat = new THREE.BoxGeometry(.75, .25, 1.65)
  couchSeat.translate(-1, 6.75, -.01)
	couchGeometry.merge(couchSeat)
  var couchBack = new THREE.BoxGeometry(.25, .75, 1.65)
  couchBack.translate(-.5, 7, -.01)
	couchGeometry.merge(couchBack)
  var armRest = new THREE.BoxGeometry(1, .5, .25)
  armRest.translate(-.87, 6.87, .92)
	couchGeometry.merge(armRest)
  armRest.translate(0, 0, -1.84)
	couchGeometry.merge(armRest)
  var cushion = new THREE.BoxGeometry(.75, .15, .5)
  cushion.translate(-1, 6.86, 0)
	couchGeometry.merge(cushion)
  cushion.translate(0, 0, -.52)
	couchGeometry.merge(cushion)
  cushion.translate(0, 0, 1.04)
	couchGeometry.merge(cushion)
  couchGeometry.rotateY(1.25)
  couchGeometry.translate(-1.25, 0, -3)
  var couchShadow = couchGeometry.clone(true)
  decorationShadows.merge(couchShadow)
  var couch = new THREE.Mesh(couchGeometry, couchFabric)
  couch.castShadow = true
  decorations.add(couch)

  var blueCouch = couchGeometry.clone(true)
  blueCouch.rotateY(2)
  blueCouch.translate(2.5, 0, -1)
  var couchShadow = blueCouch.clone(true)
  decorationShadows.merge(couchShadow)
  var couch2 = new THREE.Mesh(blueCouch, blueFabric)
  couch2.castShadow = true
  decorations.add(couch2)

  var purpleCouch = couchGeometry.clone(true)
  purpleCouch.rotateY(-1)
  purpleCouch.translate(1.5, -3.5, 1)
  var couchShadow = purpleCouch.clone(true)
  decorationShadows.merge(couchShadow)
  var couch3 = new THREE.Mesh(purpleCouch, purpleFabric)
  couch3.castShadow = true
  decorations.add(couch3)

  var tanCouch = couchGeometry.clone(true)
  tanCouch.rotateY(3.5)
  tanCouch.translate(-3.75, -3.5, .5)
  var couchShadow = tanCouch.clone(true)
  decorationShadows.merge(couchShadow)
  var couch4 = new THREE.Mesh(tanCouch, tanFabric)
  couch4.castShadow = true
  decorations.add(couch4)

  // Bed
  var bed = new THREE.Group()
  var sheets = new THREE.BoxGeometry(2, .1, 1)
  sheets.translate(-1.5, 3.7, -2)
  var sheetsSide = new THREE.BoxGeometry(2, .5, .1)
  sheetsSide.translate(-1.5, 3.5, -1.5)
  sheets.merge(sheetsSide)
  sheetsSide.translate(0, 0, -1)
  sheets.merge(sheetsSide)
  var sheetsEnd = new THREE.BoxGeometry(.1, .5, 1.1)
  sheetsEnd.translate(-.5, 3.5, -2)
  sheets.merge(sheetsEnd)
  sheets.rotateY(-1.55)
  sheets.translate(-3, 0, 0)
  var sheetsShadow = sheets.clone(true)
  decorationShadows.merge(sheetsShadow)
  var bedSheet = new THREE.Mesh(sheets, blueFabric)
  bedSheet.castShadow = true
  bed.add(bedSheet)
  var sheets2 = sheets.clone()
  sheets2.rotateY(1.55)
  sheets2.translate(3.5, 0, 1)
  var sheetsShadow = sheets2.clone(true)
  decorationShadows.merge(sheetsShadow)
  var bedSheet2 = new THREE.Mesh(sheets2, couchFabric)
  bed.add(bedSheet2)
  var sheets3 = sheets.clone()
  sheets3.rotateY(1.55)
  sheets3.translate(3.5, 3.5, -3)
  var sheetsShadow = sheets3.clone(true)
  decorationShadows.merge(sheetsShadow)
  var bedSheet3 = new THREE.Mesh(sheets3, purpleFabric)
  bed.add(bedSheet3)
  var sheets4 = sheets.clone()
  sheets4.rotateY(3.14)
  sheets4.translate(-2.05, 3.5, -.5)
  var sheetsShadow = sheets4.clone(true)
  decorationShadows.merge(sheetsShadow)
  var bedSheet4 = new THREE.Mesh(sheets4, blueFabric)
  bed.add(bedSheet4)

  var mattress = new THREE.BoxGeometry(2.5, .45, 1)
  mattress.rotateY(-1.55)
  mattress.translate(-1.02, 3.475, -1.75)
  var mattressShadow = mattress.clone(true)
  decorationShadows.merge(mattressShadow)
  var bedMattress = new THREE.Mesh(mattress, tanFabric)
  bed.add(bedMattress)
  var mattress2 = mattress.clone()
  mattress2.rotateY(1.55)
  mattress2.translate(3.3, 0, 1)
  var mattressShadow = mattress2.clone(true)
  decorationShadows.merge(mattressShadow)
  var bedMattress2 = new THREE.Mesh(mattress2, tanFabric)
  bed.add(bedMattress2)
  var mattress3 = mattress.clone()
  mattress3.rotateY(1.55)
  mattress3.translate(3.3, 3.5, -3)
  var mattressShadow = mattress3.clone(true)
  decorationShadows.merge(mattressShadow)
  var bedMattress3 = new THREE.Mesh(mattress3, tanFabric)
  bed.add(bedMattress3)
  var mattress4 = mattress.clone()
  mattress4.translate(0, 3.5, 3)
  var mattressShadow = mattress4.clone(true)
  decorationShadows.merge(mattressShadow)
  var bedMattress4 = new THREE.Mesh(mattress4, tanFabric)
  bed.add(bedMattress4)

  decorations.add(bed)

  // Lobby
  var lobbyDesk = new THREE.Geometry()
  var deskFront = new THREE.BoxGeometry(3, 1, .1)
  deskFront.translate(0, 1, -.5)
	lobbyDesk.merge(deskFront)
  var deskFront = new THREE.BoxGeometry(.1, 1, 1)
  deskFront.translate(1.45, 1, -1)
	lobbyDesk.merge(deskFront)
  deskFront.translate(-2.9, 0, 0)
	lobbyDesk.merge(deskFront)
  var deskFront = new THREE.BoxGeometry(3.2, .1, 1.2)
  deskFront.translate(0, 1.55, -1)
	lobbyDesk.merge(deskFront)
  var deskFront = new THREE.BoxGeometry(3.1, .1, 1.1)
  deskFront.translate(0, 1.65, -1)
	lobbyDesk.merge(deskFront)
  var lobbyShadow = lobbyDesk.clone(true)
  decorationShadows.merge(lobbyShadow)
  var lobby = new THREE.Mesh(lobbyDesk, stone)
  decorations.add(lobby)

  var interiorShadows = new THREE.Mesh(decorationShadows, shadows)
  interiorShadows.receiveShadow = true
  office.add(interiorShadows)

  office.add(decorations)

  // Add to scene
  office.position.set(-11, .75, -9) //-10, -.5, -6
	//office.scale.set(1.7, 1.7, 1.7)
  scene.add(office)
}
