function initShop()  {

  var shop = new THREE.Group()
  var shopBase = new THREE.Geometry()
  var shopShadowGeometry = new THREE.Geometry()

// Foundation
  var bottom = new THREE.BoxGeometry(10, 1, 5)
  shopBase.merge(bottom)
  var bottomStair = new THREE.BoxGeometry(2, .5, .5)
  bottomStair.translate(0, .25, 2.75)
  shopBase.merge(bottomStair)
  var topStair = new THREE.BoxGeometry(2, .5, 1)
  topStair.translate(0, -.25, 3)
  shopBase.merge(topStair)
  var shopBaseShadow = shopBase.clone()
  shopShadowGeometry.merge(shopBaseShadow)
  var building = new THREE.Mesh(shopBase, foundation)
	building.castShadow = true
  shop.add(building)

// Building
  var glass = new THREE.BoxGeometry(9.75, 4.9, .125)
  glass.translate(0, 3, 2.4)
  var windows = new THREE.Mesh(glass, windowColor)
  shop.add(windows)

  var shopCore = new THREE.Geometry()
  var bottomFront = new THREE.BoxGeometry(4, 1, .75)
  bottomFront.translate(-3, 1, 2.125)
  shopCore.merge(bottomFront)
  bottomFront.translate(6, 0, 0)
  shopCore.merge(bottomFront)
  var topFront = new THREE.BoxGeometry(10, 2, .75)
  topFront.translate(0, 5, 2.12)
  shopCore.merge(topFront)
  var sides = new THREE.BoxGeometry(1, 5.5, 3.25)
  sides.translate(-4.5, 3.25, .126)
  shopCore.merge(sides)
  sides.translate(9, 0, 0)
  shopCore.merge(sides)
  var inner = new THREE.BoxGeometry(1, 2.5, .5)
  inner.translate(-1.5, 2.75, 2.25)
  shopCore.merge(inner)
  inner.translate(3, 0, 0)
  shopCore.merge(inner)
  var center = new THREE.BoxGeometry(10, 5.5, 1)
  center.translate(0, 3.25, -2)
  shopCore.merge(center)
  var top = new THREE.BoxGeometry(8, 1, 3.25)
  top.translate(0, 5.5, .125)
  shopCore.merge(top)
  var coreShopShadow = shopCore.clone()
  shopShadowGeometry.merge(coreShopShadow)
  var building = new THREE.Mesh(shopCore, stone)
	building.castShadow = true
  shop.add(building)

// Insides

  var insideShadowGeometry = new THREE.Geometry()

  var counter = new THREE.BoxGeometry(3, 1.5, 1)
  counter.translate(0, 1.25, 0)
  var coreCountersShadow = counter.clone()
  insideShadowGeometry.merge(coreCountersShadow)
  var Counters = new THREE.Mesh(counter, stone)
  shop.add(Counters)

  var shelf = new THREE.BoxGeometry(.5, .1, 3)
  shelf.translate(3.75, 2, 0)
  var shelf2 = new THREE.BoxGeometry(.5, .1, 3)
  shelf2.translate(3.75, 3, 0)
  shelf.merge(shelf2)
  shelf2.translate(0, 1, 0)
  shelf.merge(shelf2)
  shelf2.translate(-7.5, 0, 0)
  shelf.merge(shelf2)
  shelf2.translate(0, -1, 0)
  shelf.merge(shelf2)
  shelf2.translate(0, -1, 0)
  shelf.merge(shelf2)
  var coreShelvesShadow = shelf.clone()
  insideShadowGeometry.merge(coreShelvesShadow)
  var shelves = new THREE.Mesh(shelf, stone)
  shop.add(shelves)

  var book1 = new THREE.BoxGeometry(.7, .75, .2)
  book1.translate(3.75, 3.45, 0)
  var book2 = new THREE.BoxGeometry(.7, .75, .2)
  book2.translate(3.75, 3.45, 1)
  book1.merge(book2)
  book2.translate(0, 1, -1.5)
  book1.merge(book2)
  book2.translate(0, -2, -.5)
  book1.merge(book2)
  book2.translate(0, 0, .75)
  book1.merge(book2)
  book2.translate(0, 0, 1)
  book1.merge(book2)
  book2.translate(-7.5, 0, 0)
  book1.merge(book2)
  book2.translate(0, 0, -1.5)
  book1.merge(book2)
  book2.translate(0, 1, .5)
  book1.merge(book2)
  book2.translate(0, 0, .75)
  book1.merge(book2)
  book2.translate(0, 1, .25)
  book1.merge(book2)
  book2.translate(0, 0, -.75)
  book1.merge(book2)
  book2.translate(0, 0, -.5)
  book1.merge(book2)
  var book7 = new THREE.BoxGeometry(.7, .75, .2)
  book7.translate(-3.5, 1.87, 2.25)
  book1.merge(book7)
  var coreRedShadow = book1.clone()
  insideShadowGeometry.merge(coreRedShadow)
  var redBooks = new THREE.Mesh(book1, red)
  redBooks.castShadow = true
  shop.add(redBooks)

  var books2 = new THREE.Geometry()
  var book3 = new THREE.BoxGeometry(.7, .75, .2)
  book3.translate(3.75, 3.45, 1.2)
  books2.merge(book3)
  book3.translate(0, 1, -1.5)
  books2.merge(book3)
  book3.translate(0, -2, -.5)
  books2.merge(book3)
  book3.translate(0, 0, .75)
  books2.merge(book3)
  book3.translate(0, 0, 1)
  books2.merge(book3)
  book3.translate(-7.5, 0, 0)
  books2.merge(book3)
  book3.translate(0, 0, -1.5)
  books2.merge(book3)
  book3.translate(0, 1, .5)
  books2.merge(book3)
  book3.translate(0, 0, .75)
  books2.merge(book3)
  book3.translate(0, 1, .25)
  books2.merge(book3)
  book3.translate(0, 0, -.75)
  books2.merge(book3)
  book3.translate(0, 0, -.5)
  books2.merge(book3)
  var book8 = new THREE.BoxGeometry(.7, .75, .2)
  book8.translate(-2.5, 1.87, 2.25)
  books2.merge(book8)
  var coreBlueShadow = books2.clone()
  insideShadowGeometry.merge(coreBlueShadow)
  var blueBooks = new THREE.Mesh(books2, blue)
  blueBooks.castShadow = true
  shop.add(blueBooks)

  var books3 = new THREE.Geometry()
  var book4 = new THREE.BoxGeometry(.7, .75, .2)
  book4.translate(3.75, 3.45, 1.4)
  books3.merge(book4)
  book4.translate(0, 1, -1.5)
  books3.merge(book4)
  book4.translate(0, -2, -.5)
  books3.merge(book4)
  book4.translate(0, 0, .75)
  books3.merge(book4)
  book4.translate(0, 0, 1)
  books3.merge(book4)
  book4.translate(-7.5, 0, 0)
  books3.merge(book4)
  book4.translate(0, 0, -1.5)
  books3.merge(book4)
  book4.translate(0, 1, .5)
  books3.merge(book4)
  book4.translate(0, 0, .75)
  books3.merge(book4)
  book4.translate(0, 1, .25)
  books3.merge(book4)
  book4.translate(0, 0, -.75)
  books3.merge(book4)
  book4.translate(0, 0, -1.5)
  books3.merge(book4)
  book4.translate(7.5, 0, 2)
  books3.merge(book4)
  book4.translate(0, -1, -1.75)
  books3.merge(book4)
  var corePurpleShadow = books3.clone()
  insideShadowGeometry.merge(corePurpleShadow)
  var purpleBooks = new THREE.Mesh(books3, purple)
  purpleBooks.castShadow = true
  shop.add(purpleBooks)

  var books4 = new THREE.Geometry()
  var book5 = new THREE.BoxGeometry(.7, .75, .2)
  book5.translate(3.75, 3.45, .6)
  books4.merge(book5)
  book5.translate(0, 0, -1)
  books4.merge(book5)
  book5.translate(0, 1, -.75)
  books4.merge(book5)
  book5.translate(0, 0, 1.5)
  books4.merge(book5)
  book5.translate(0, 0, .75)
  books4.merge(book5)
  book5.translate(-7.5, -1, -1.75)
  books4.merge(book5)
  book5.translate(0, -1, -.5)
  books4.merge(book5)
  book5.translate(0, 0, 1.5)
  books4.merge(book5)
  var book6 = new THREE.BoxGeometry(.7, .75, .2)
  book6.translate(3.5, 1.87, 2.25)
  books4.merge(book6)
  var coreOrangeShadow = books4.clone()
  insideShadowGeometry.merge(coreOrangeShadow)
  var orangeBooks = new THREE.Mesh(books4, orange)
  orangeBooks.castShadow = true
  shop.add(orangeBooks)
  var shopInsideShadow = new THREE.Mesh(insideShadowGeometry, shadows)
  shopInsideShadow.receiveShadow = true
  shop.add(shopInsideShadow)

// Awning
  // White Stripes
  var awningA = new THREE.Geometry()
  var aA1 = new THREE.BoxGeometry(1.1, 1.25, 2)
  aA1.translate(-4.4, 5.25, 3.5)
  aA1.vertices[0].y-=.9;
  aA1.vertices[5].y-=.9;
  awningA.merge(aA1)
  aA1.translate(2.2, 0, 0)
  awningA.merge(aA1)
  aA1.translate(2.2, 0, 0)
  awningA.merge(aA1)
  aA1.translate(2.2, 0, 0)
  awningA.merge(aA1)
  aA1.translate(2.2, 0, 0)
  awningA.merge(aA1)
  var aShadow = awningA.clone()
  shopShadowGeometry.merge(aShadow)
  var As = new THREE.Mesh(awningA, offwhite)
  As.castShadow = true
  // Red Stripes
  var awningB = new THREE.Geometry()
  var aB1 = new THREE.BoxGeometry(1.1, 1.25, 2)
  aB1.translate(-3.3, 5.25, 3.5)
  aB1.vertices[0].y-=.9;
  aB1.vertices[5].y-=.9;
  awningB.merge(aB1)
  aB1.translate(2.2, 0, 0)
  awningB.merge(aB1)
  aB1.translate(2.2, 0, 0)
  awningB.merge(aB1)
  aB1.translate(2.2, 0, 0)
  awningB.merge(aB1)
  var bShadow = awningB.clone()
  shopShadowGeometry.merge(bShadow)
  var Bs = new THREE.Mesh(awningB, blue)
  Bs.castShadow = true
  shop.add(As)
  shop.add(Bs)
  var shopShadow = new THREE.Mesh(shopShadowGeometry, shadows)
  shopShadow.receiveShadow = true
  shop.add(shopShadow)

// Add To Scene
  shop.position.set(8, 1, -8) // 8, -9
  scene.add(shop)

}
